# sonic-pwmd (SONiC PWM daemon) Debian package

# SONIC_PWMD_PY3 package

SONIC_PWMD_PY3 = sonic_pwmd-1.0-py3-none-any.whl
$(SONIC_PWMD_PY3)_SRC_PATH = $(SRC_PATH)/sonic-platform-daemons/sonic-pwmd
$(SONIC_PWMD_PY3)_DEPENDS = $(SONIC_PY_COMMON_PY3) $(SONIC_PLATFORM_COMMON_PY3)
$(SONIC_PWMD_PY3)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(SONIC_PWMD_PY3)_PYTHON_VERSION = 3
SONIC_PYTHON_WHEELS += $(SONIC_PWMD_PY3)
